export PATH=$HOME/clickhouse:$HOME/.cargo/bin:$HOME/.local/cmake-3.25.1-linux-x86_64/bin:$HOME/local/bin:/usr/local/go/bin:$HOME/go/bin:$PATH

# set vim as default editor
export VISUAL=vim
export EDITOR="$VISUAL"

if [ -x "$(command -v /opt/homebrew/bin/brew)" ]; then
    # MacOS: prefer Clang from Homebrew over Apple's Clang
    export PATH=$(brew --prefix llvm)/bin:$PATH
    export CC=$(brew --prefix llvm)/bin/clang
    export CXX=$(brew --prefix llvm)/bin/clang++
    export CH_CORES_FOR_COMPILATION=10
else
    # Linux:
    export CC=clang-15 CXX=clang++-15
    export CH_CORES_FOR_COMPILATION=32
fi

# CH_SHARED_LIBS="-DUSE_STATIC_LIBRARIES=0 -DSPLIT_SHARED_LIBRARIES=1"
CH_SHARED_LIBS=""

CH_SLIM_BUILD_OPTIONS="-DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DENABLE_EXAMPLES=0 -DENABLE_HIVE=0 -DENABLE_HDFS=0 -DENABLE_AVRO=0 -DENABLE_GRPC=0 -DENABLE_PARQUET=1 -DENABLE_ROCKSDB=0 -DENABLE_MYSQL=0 -DENABLE_KAFKA=0 -DENABLE_PROTOBUF=0 -DCOMPILER_CACHE=auto -DENABLE_TESTS=0 -DENABLE_UTILS=0 -DENABLE_CLICKHOUSE_SELF_EXTRACTING=0 -DENABLE_CLICKHOUSE_COMPRESSOR=0 -DENABLE_CLICKHOUSE_ODBC_BRIDGE=0 -DENABLE_CLICKHOUSE_LIBRARY_BRIDGE=0 -DENABLE_THINLTO=0 -DENABLE_CLICKHOUSE_GIT_IMPORT=0 -DENABLE_CLICKHOUSE_DISKS=0 -DENABLE_CLICKHOUSE_SU=0 -DBUILD_STANDALONE_KEEPER=0"
CH_FAT_BUILD_OPTIONS="-DENABLE_HDFS=0 -DENABLE_AVRO=1 -DENABLE_GRPC=1 -DENABLE_PARQUET=1 -DENABLE_ROCKSDB=1 -DENABLE_MYSQL=0 -DENABLE_KAFKA=1 -DENABLE_PROTOBUF=1 -DCOMPILER_CACHE=auto" # MySQL: "The deprecated ucontext routines require _XOPEN_SOURCE to be defined"
CH_UBSAN="-DSANITIZE=undefined -DENABLE_JEMALLOC=0"
CH_MSAN="-DSANITIZE=memory -DENABLE_JEMALLOC=0"

CH_BUILD_TYPE_DEBUG="-DCMAKE_BUILD_TYPE=Debug"
CH_BUILD_TYPE_RELDBG="-DCMAKE_BUILD_TYPE=RelWithDebInfo"

CH_PATH_TO_SOURCE="-S ."
CH_PATH_TO_DEBUG="debug"
CH_PATH_TO_RELDBG="reldbg"
CH_PATH_TO_RELDBG_OPT_VIEWER="reldbg_opt_viewer"
CH_PATH_TO_DEBUG_UBSAN="debug_ubsan"
CH_PATH_TO_RELDBG_UBSAN="reldbg_ubsan"
CH_PATH_TO_RELDBG_MSAN="reldbg_msan"
CH_PATH_TO_RELDBG_TSAN="reldbg_tsan"

alias make_debug="cmake ${CH_SHARED_LIBS} ${CH_SLIM_BUILD_OPTIONS} ${CH_BUILD_TYPE_DEBUG} ${CH_PATH_TO_SOURCE} -B ${CH_PATH_TO_DEBUG}"
alias make_debug_fat="cmake ${CH_SHARED_LIBS} ${CH_FAT_BUILD_OPTIONS} ${CH_BUILD_TYPE_DEBUG} ${CH_PATH_TO_SOURCE} -B ${CH_PATH_TO_DEBUG}"
alias make_debug_ubsan="cmake ${CH_SHARED_LIBS} ${CH_SLIM_BUILD_OPTIONS} ${CH_UBSAN} ${CH_BUILD_TYPE_DEBUG} ${CH_PATH_TO_SOURCE} -B ${CH_PATH_TO_DEBUG_UBSAN}"
alias make_reldbg="cmake ${CH_SHARED_LIBS} ${CH_SLIM_BUILD_OPTIONS} -DCMAKE_CXX_FLAGS_ADD="-fno-omit-frame-pointer" ${CH_BUILD_TYPE_RELDBG} ${CH_PATH_TO_SOURCE} -B ${CH_PATH_TO_RELDBG}"
alias make_reldbg_fat="cmake ${CH_SHARED_LIBS} ${CH_FAT_BUILD_OPTIONS} -DCMAKE_CXX_FLAGS_ADD="-fno-omit-frame-pointer" ${CH_BUILD_TYPE_RELDBG} ${CH_PATH_TO_SOURCE} -B ${CH_PATH_TO_RELDBG}"
alias make_reldbg_ubsan="cmake ${CH_SHARED_LIBS} ${CH_SLIM_BUILD_OPTIONS} ${CH_UBSAN} ${CH_BUILD_TYPE_RELDBG} ${CH_PATH_TO_SOURCE} -B ${CH_PATH_TO_RELDBG_UBSAN}"
alias make_reldbg_msan="cmake ${CH_SHARED_LIBS} ${CH_SLIM_BUILD_OPTIONS} ${CH_MSAN} ${CH_BUILD_TYPE_RELDBG} ${CH_PATH_TO_SOURCE} -B ${CH_PATH_TO_RELDBG_MSAN}"
alias make_reldbg_opt_viewer="cmake ${CH_SHARED_LIBS} ${CH_SLIM_BUILD_OPTIONS} -DCMAKE_CXX_FLAGS_ADD="-fsave-optimization-record" ${CH_BUILD_TYPE_RELDBG} ${CH_PATH_TO_SOURCE} -B ${CH_PATH_TO_RELDBG_OPT_VIEWER}"

alias cdebug="cmake --build ${CH_PATH_TO_DEBUG} -j${CH_CORES_FOR_COMPILATION} -- "
alias cdebug_ubsan="cmake --build ${CH_PATH_TO_DEBUG_UBSAN} -j${CH_CORES_FOR_COMPILATION} -- "
alias creldbg="cmake --build ${CH_PATH_TO_RELDBG} -j${CH_CORES_FOR_COMPILATION} -- "
alias creldbg_ubsan="cmake --build ${CH_PATH_TO_RELDBG_UBSAN} -j${CH_CORES_FOR_COMPILATION} -- "
alias creldbg_msan="cmake --build ${CH_PATH_TO_RELDBG_MSAN} -j${CH_CORES_FOR_COMPILATION} -- "
