export PATH=$HOME/cmake-3.24.2-linux-x86_64/bin:/usr/local/go/bin:$HOME/go/bin:$PATH

if [ -x "$(command -v /opt/homebrew/bin/brew)" ]; then
    # MacOS: prefer Clang from Homebrew over Apple's Clang
    export PATH=$(brew --prefix llvm)/bin:$PATH
    export CC=$(brew --prefix llvm)/bin/clang
    export CXX=$(brew --prefix llvm)/bin/clang++
    export CH_CORES_FOR_COMPILATION=10
else
    # Linux:
    export CC=clang-15 CXX=clang++-15
    export CH_CORES_FOR_COMPILATION=32
fi

# CH_SHARED_LIBS="-DUSE_STATIC_LIBRARIES=0 -DSPLIT_SHARED_LIBRARIES=1"
CH_SHARED_LIBS=""

CH_SLIM_BUILD_OPTIONS="-DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DENABLE_EXAMPLES=0 -DENABLE_HIVE=0 -DENABLE_HDFS=0 -DENABLE_S3=0 -DENABLE_AVRO=0 -DENABLE_GRPC=0 -DENABLE_PARQUET=0 -DENABLE_ROCKSDB=0 -DENABLE_MYSQL=0 -DENABLE_KAFKA=0 -DENABLE_PROTOBUF=0 -DENABLE_CCACHE=1 -DENABLE_TESTS=1 -DENABLE_UTILS=0 -DENABLE_CLICKHOUSE_SELF_EXTRACTING=0 -DENABLE_CLICKHOUSE_COMPRESSOR=0 -DENABLE_CLICKHOUSE_ODBC_BRIDGE=0 -DENABLE_CLICKHOUSE_LIBRARY_BRIDGE=0 -DENABLE_THINLTO=0 -DENABLE_CLICKHOUSE_GIT_IMPORT=0 -DENABLE_CLICKHOUSE_DISKS=0 -DENABLE_CLICKHOUSE_SU=0 -DBUILD_STANDALONE_KEEPER=1"
CH_FAT_BUILD_OPTIONS="-DENABLE_HDFS=1 -DENABLE_S3=1 -DENABLE_AVRO=1 -DENABLE_GRPC=1 -DENABLE_PARQUET=1 -DENABLE_ROCKSDB=1 -DENABLE_MYSQL=0 -DENABLE_KAFKA=1 -DENABLE_PROTOBUF=1 -DENABLE_CCACHE=1" # MySQL: "The deprecated ucontext routines require _XOPEN_SOURCE to be defined"
CH_UBSAN="-DSANITIZE=undefined -DENABLE_JEMALLOC=0"

CH_BUILD_TYPE_DEBUG="-DCMAKE_BUILD_TYPE=Debug"
CH_BUILD_TYPE_RELDBG="-DCMAKE_BUILD_TYPE=RelWithDebInfo"

CH_PATH_TO_SOURCE="-S ."
CH_PATH_TO_DEBUG="debug"
CH_PATH_TO_RELDBG="reldbg"
CH_PATH_TO_DEBUG_UBSAN="debug_ubsan"
CH_PATH_TO_RELDBG_UBSAN="reldbg_ubsan"

alias make_debug="cmake ${CH_GENERATOR} ${CH_SHARED_LIBS} ${CH_SLIM_BUILD_OPTIONS} ${CH_BUILD_TYPE_DEBUG} ${CH_PATH_TO_SOURCE} -B ${CH_PATH_TO_DEBUG}"
alias make_debug_ubsan="cmake ${CH_GENERATOR} ${CH_SHARED_LIBS} ${CH_SLIM_BUILD_OPTIONS} ${CH_UBSAN} ${CH_BUILD_TYPE_DEBUG} ${CH_PATH_TO_SOURCE} -B ${CH_PATH_TO_DEBUG_UBSAN}"
alias make_reldbg="cmake ${CH_GENERATOR} ${CH_SHARED_LIBS} ${CH_SLIM_BUILD_OPTIONS} ${CH_BUILD_TYPE_RELDBG} ${CH_PATH_TO_SOURCE} -B ${CH_PATH_TO_RELDBG}"
alias make_reldbg_ubsan="cmake ${CH_GENERATOR} ${CH_SHARED_LIBS} ${CH_SLIM_BUILD_OPTIONS} ${CH_UBSAN} ${CH_BUILD_TYPE_RELDBG} ${CH_PATH_TO_SOURCE} -B ${CH_PATH_TO_RELDBG_UBSAN}"

alias cdebug="cmake --build ${CH_PATH_TO_DEBUG} -j${CH_CORES_FOR_COMPILATION} -- "
alias cdebug_ubsan="cmake --build ${CH_PATH_TO_DEBUG_UBSAN} -j${CH_CORES_FOR_COMPILATION} -- "
alias creldbg="cmake --build ${CH_PATH_TO_RELDBG} -j${CH_CORES_FOR_COMPILATION} -- "
alias creldbg_ubsan="cmake --build ${CH_PATH_TO_RELDBG_UBSAN} -j${CH_CORES_FOR_COMPILATION} -- "
